### ISSUE TITLE
Auto determine hook based on WP Environment

### ISSUE THREAD

**Issue by elliottpost** [aderaaij/wp-vercel-deploy-hooks#10]
Given the use case of having a different Vercel deploy hook for various environments and git branches, say one for `main`, one for `test`, and another for `development`, it's not currently possible with the plugin to configure these based on environment. 

Using a WP host like Pantheon, Acquia, or WPEngine where multiple environments are built in and pair directly with preview environments/branches in Vercel/git, this represents a challenge because every time a site is pushed from one environment to another the Vercel URL is overwritten.

I have created a PR that I'll attach here in a moment that solves this by allowing a user to set these values in wp-config.php or anywhere else that runs before this plugin.

**Comment by aderaaij** [comment]
Well it only took 4 months but it's merged. Thanks again for the contribution! It's greatly appreciated 🙏
