### ISSUE TITLE
support for multiple webhook?

### ISSUE THREAD

**Issue by vasilenka** [aderaaij/wp-vercel-deploy-hooks#3]
I've 2 deployments depend on a single Wordpress
How to add 2 endpoints to the plugin?

**Comment by aderaaij** [comment]
Heya, thanks for reporting this! Actually this is a very valid use case that i hadn't considered yet. When I have some time I can have a look at adding support for this (or feel free to make a PR.

**Comment by aderaaij** [comment]
@vasilenka I think this could now work for you by ading environment endpoints in the wp-config file (see readme.md). Hope that helps!
