### ISSUE TITLE
Let editor user build

### ISSUE THREAD

**Issue by matteofrana** [aderaaij/wp-vercel-deploy-hooks#9]
Hi!
Thank you for this great plugin.
I'd like to let the Editor user build the website after an editing session, without triggering a build on each save.
Having the "build" button for the Editor user would be great.

Is it something you could do or have on your roadmap?

Thank you,
Matteo

**Comment by aderaaij** [comment]
Hi Matteo, thanks for the kind words and suggestion! Actually, thanks to [this PR](https://github.com/aderaaij/wp-vercel-deploy-hooks/pull/4) you should already be able to do this. You can use a plugin like "User Role Editor" and select the `vercel_deploy_capability` for the editor role. Let me know if that works out for you!

**Comment by aderaaij** [comment]
I'm assuming my suggestion took care of this :)
